"""empty message

Revision ID: 096490c75f1b
Revises: d95f0c89c09f
Create Date: 2023-07-07 16:15:30.481744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096490c75f1b'
down_revision = 'd95f0c89c09f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
