"""empty message

Revision ID: 26231001a6ad
Revises: 096490c75f1b
Create Date: 2023-07-10 08:10:21.332656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26231001a6ad'
down_revision = '096490c75f1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
