"""empty message

Revision ID: 3778eaec79d1
Revises: d117a987ca83
Create Date: 2023-07-10 09:46:25.538019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3778eaec79d1'
down_revision = 'd117a987ca83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
