"""empty message

Revision ID: a8a1f26e13b6
Revises: 26231001a6ad
Create Date: 2023-07-10 08:12:09.368227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a1f26e13b6'
down_revision = '26231001a6ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
