"""empty message

Revision ID: c1bf08fc0931
Revises: f26b86714644
Create Date: 2023-07-06 09:31:23.504095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bf08fc0931'
down_revision = 'f26b86714644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
