"""empty message

Revision ID: c4a4ab395b18
Revises: 39fbde0d6050
Create Date: 2023-07-10 08:19:11.139921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a4ab395b18'
down_revision = '39fbde0d6050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
