"""empty message

Revision ID: d117a987ca83
Revises: c4a4ab395b18
Create Date: 2023-07-10 08:21:45.659527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd117a987ca83'
down_revision = 'c4a4ab395b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
