"""empty message

Revision ID: d95f0c89c09f
Revises: c1bf08fc0931
Create Date: 2023-07-07 06:54:05.629522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95f0c89c09f'
down_revision = 'c1bf08fc0931'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
